package visao;

import Transformacoes.TransformacoesAutomato;
import automatoFinito.AutomatoFinito;
import expressaoRegular.Arvore;
import expressaoRegular.ExpressaoRegular;
import java.util.Arrays;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import gramatica.modelo.Gramatica;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

    Object[][] dataAutomato = null;
    Object[][] dataGramatica = null;
    Object[][] dataAutomatoER = null;
    String[] nomeColunasAutomato = new String[1];
    String[] nomeColunasAutomatoER = new String[3];
    String[] nomeColunasGramatica = new String[3];
    DefaultTableModel modeloGramatica, modeloAutomato, modeloAutomatoER;
    Gramatica gramatica;
    AutomatoFinito automato;
    AutomatoFinito automatoER;
    ExpressaoRegular expressaoRegular = new ExpressaoRegular();


    public TelaPrincipal() {
        automato = new AutomatoFinito();
        automatoER = new AutomatoFinito();
        gramatica = new Gramatica();
        initComponents();
        nomeColunasAutomato[0] = "δ";
        nomeColunasAutomatoER[0] = "δ";
        nomeColunasGramatica[0] = "N";
        nomeColunasGramatica[1] = "Nao-Terminais";
        nomeColunasGramatica[2] = "Lado Direito da Producao";
        dataAutomato = new Object[0][0];
        dataGramatica = new Object[0][0];
        dataAutomatoER = new Object[0][0];
        inicializarComponentes();
    }

    public void inicializarComponentes() {
        modeloGramatica = new DefaultTableModel(dataGramatica, nomeColunasGramatica);
        modeloAutomato = new DefaultTableModel(dataAutomato, nomeColunasAutomato);
        modeloAutomatoER = new DefaultTableModel(dataAutomatoER, nomeColunasAutomatoER);
        tabelaExpressaoAutomato.setModel(modeloAutomatoER);
        tabelaGramatica.setModel(modeloGramatica);
        tabelaAutomato.setModel(modeloAutomato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGramatica = new javax.swing.JTable();
        adicionarLinhaGramatica = new javax.swing.JButton();
        salvarGramatica = new javax.swing.JButton();
        resetarGramatica = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ER = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaExpressaoAutomato = new javax.swing.JTable();
        transformarER = new javax.swing.JButton();
        resetarER = new javax.swing.JButton();
        gramaticaAutomato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        adicionarLinhaAutomato = new javax.swing.JButton();
        resetaAutomato = new javax.swing.JButton();
        salvarAutomato = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        determinizar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        complementar = new javax.swing.JButton();
        interseccao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAutomato = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabelaGramatica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaGramatica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N", "Não - Terminais", "Lado Direito da Produção"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaGramatica.setToolTipText("");
        tabelaGramatica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaGramatica.setFocusable(false);
        tabelaGramatica.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaGramatica.setInheritsPopupMenu(true);
        tabelaGramatica.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tabelaGramatica);
        if (tabelaGramatica.getColumnModel().getColumnCount() > 0) {
            tabelaGramatica.getColumnModel().getColumn(0).setResizable(false);
            tabelaGramatica.getColumnModel().getColumn(0).setPreferredWidth(3);
            tabelaGramatica.getColumnModel().getColumn(1).setResizable(false);
            tabelaGramatica.getColumnModel().getColumn(1).setHeaderValue("Não - Terminais");
            tabelaGramatica.getColumnModel().getColumn(2).setHeaderValue("Lado Direito da Produção");
        }

        adicionarLinhaGramatica.setText("Adicionar Nova Linha");
        adicionarLinhaGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarLinhaGramaticaActionPerformed(evt);
            }
        });

        salvarGramatica.setText("Salvar");
        salvarGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarGramaticaActionPerformed(evt);
            }
        });

        resetarGramatica.setText("Resetar Gramática");
        resetarGramatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarGramaticaActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Gramática Regular:");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Expressão Regular:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        ER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERActionPerformed(evt);
            }
        });

        tabelaExpressaoAutomato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaExpressaoAutomato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaExpressaoAutomato.setToolTipText("");
        tabelaExpressaoAutomato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaExpressaoAutomato.setFocusable(false);
        tabelaExpressaoAutomato.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaExpressaoAutomato.setInheritsPopupMenu(true);
        tabelaExpressaoAutomato.getTableHeader().setReorderingAllowed(false);
        tabelaExpressaoAutomato.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(tabelaExpressaoAutomato);

        transformarER.setText("Transformar ER para AF");
        transformarER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformarERActionPerformed(evt);
            }
        });

        resetarER.setText("Resetar ER/AF");
        resetarER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarERActionPerformed(evt);
            }
        });

        gramaticaAutomato.setText("GR -> AF");
        gramaticaAutomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gramaticaAutomatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(ER)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(transformarER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetarER))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(resetarGramatica, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(adicionarLinhaGramatica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3))
                                .addGap(49, 49, 49)
                                .addComponent(gramaticaAutomato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salvarGramatica)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarLinhaGramatica)
                    .addComponent(salvarGramatica, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gramaticaAutomato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetarGramatica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transformarER)
                    .addComponent(resetarER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField5.setEditable(false);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Autômato Finito: (Principal)");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        adicionarLinhaAutomato.setText("Adicionar Nova Linha");
        adicionarLinhaAutomato.setEnabled(false);
        adicionarLinhaAutomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarLinhaAutomatoActionPerformed(evt);
            }
        });

        resetaAutomato.setText("Criar Novo Automato");
        resetaAutomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetaAutomatoActionPerformed(evt);
            }
        });

        salvarAutomato.setText("Salvar");
        salvarAutomato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAutomatoActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        determinizar.setText("Determinizar");
        determinizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                determinizarActionPerformed(evt);
            }
        });

        minimizar.setText("Minimizar");
        minimizar.setPreferredSize(new java.awt.Dimension(93, 23));
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });

        complementar.setText("Complementar");
        complementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementarActionPerformed(evt);
            }
        });

        interseccao.setText("Interseccao");
        interseccao.setToolTipText("");
        interseccao.setPreferredSize(new java.awt.Dimension(93, 23));

        jButton2.setText("AF -> GR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(determinizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(complementar, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(interseccao, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(minimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(determinizar)
                    .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementar)
                    .addComponent(interseccao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabelaAutomato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaAutomato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaAutomato.setToolTipText("");
        tabelaAutomato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaAutomato.setFocusable(false);
        tabelaAutomato.setGridColor(new java.awt.Color(0, 0, 0));
        tabelaAutomato.setInheritsPopupMenu(true);
        tabelaAutomato.getTableHeader().setReorderingAllowed(false);
        tabelaAutomato.setUpdateSelectionOnSort(false);
        jScrollPane3.setViewportView(tabelaAutomato);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(adicionarLinhaAutomato)
                        .addGap(62, 62, 62)
                        .addComponent(resetaAutomato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvarAutomato)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarLinhaAutomato)
                    .addComponent(resetaAutomato)
                    .addComponent(salvarAutomato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Alunos: Eduardo Beckhauser e Marcio Monteiro");
        jTextField1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarGramaticaActionPerformed
        gramatica.resetarGramatica();
        int numLinhas = tabelaGramatica.getRowCount();
        int numColunas = tabelaGramatica.getColumnCount();
        dataGramatica = new Object[tabelaGramatica.getRowCount()][tabelaGramatica.getColumnCount()];
        System.out.println(numLinhas + " " + numColunas);
        for (int i = 0; i < tabelaGramatica.getRowCount(); i++) {
            for (int j = 0; j < tabelaGramatica.getColumnCount(); j++) {
                dataGramatica[i][j] = tabelaGramatica.getValueAt(i, j);
            }
        }
        gramatica.tratarDadosEntrada(dataGramatica, numLinhas, numColunas);
    }//GEN-LAST:event_salvarGramaticaActionPerformed

    private void adicionarLinhaGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarLinhaGramaticaActionPerformed
        modeloGramatica.addRow(new Object[]{tabelaGramatica.getRowCount() + 1, "", ""});
    }//GEN-LAST:event_adicionarLinhaGramaticaActionPerformed

    private void resetarGramaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarGramaticaActionPerformed
        modeloGramatica.setRowCount(0);
        gramatica.resetarGramatica();
    }//GEN-LAST:event_resetarGramaticaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void adicionarLinhaAutomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarLinhaAutomatoActionPerformed
        modeloAutomato.addRow(new Object[]{""});
    }//GEN-LAST:event_adicionarLinhaAutomatoActionPerformed

    private void resetaAutomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetaAutomatoActionPerformed
        automato.resetarAutomato();
        String alfabeto = retornaAlfabeto();
        if (alfabeto == null) {
            return;
        }
        while (alfabeto.isEmpty()) {
            alfabeto = retornaAlfabeto();
        }

        List<String> nomeSimbolos = Arrays.asList(alfabeto.split("\\,"));
        for (String s : nomeSimbolos) {
            automato.alfabeto.add(s.charAt(0));
        }

        adicionarLinhaAutomato.setEnabled(true);
        criarColunasAPartirDoAlfabeto();
    }//GEN-LAST:event_resetaAutomatoActionPerformed

    private void salvarAutomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAutomatoActionPerformed
        int numLinhas = tabelaAutomato.getRowCount();
        int numColunas = tabelaAutomato.getColumnCount();
        dataAutomato = new Object[tabelaAutomato.getRowCount()][tabelaAutomato.getColumnCount()];
        System.out.println(numLinhas + " " + numColunas);
        for (int i = 0; i < tabelaAutomato.getRowCount(); i++) {
            for (int j = 0; j < tabelaAutomato.getColumnCount(); j++) {
                dataAutomato[i][j] = tabelaAutomato.getValueAt(i, j);
            }
        }
        automato.tratarDadosEntrada(dataAutomato, numLinhas, numColunas);
    }//GEN-LAST:event_salvarAutomatoActionPerformed

    private void determinizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_determinizarActionPerformed
       TransformacoesAutomato.determinizar(automato);
    }//GEN-LAST:event_determinizarActionPerformed

    private void complementarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementarActionPerformed
        Transformacoes.TransformacoesAutomato tAut = new TransformacoesAutomato();
        tAut.complementar(automato);
    }//GEN-LAST:event_complementarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
            TransformacoesAutomato.minimizar(automato);
    }//GEN-LAST:event_minimizarActionPerformed

    private void resetarERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarERActionPerformed
        ER.setText("");
        modeloAutomatoER.setRowCount(0);
    }//GEN-LAST:event_resetarERActionPerformed

    private void ERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERActionPerformed
         ER.getText();
    }//GEN-LAST:event_ERActionPerformed

    private void gramaticaAutomatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gramaticaAutomatoActionPerformed

    }//GEN-LAST:event_gramaticaAutomatoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Gramatica g = Transformacoes.Transformacoes.automatoParaGramatica(automato);
       modeloGramatica.setRowCount(0);
       gramatica = g;
       //falta passar a info pra tela
    }//GEN-LAST:event_jButton2ActionPerformed

    private void transformarERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformarERActionPerformed
        AutomatoFinito afFromER = expressaoRegular.montaAutomato(new Arvore(ER.getText()));
    }//GEN-LAST:event_transformarERActionPerformed

    //GRAMATICA
    /**
     * Adiciona um novo conjunto de producoes da gramatica a partir dos dados
     * digitados pelo usuario.
     *
     * @param s Producao a ser inserida na gramatica
     * @param producao Producao à qual deve-se inserir um naoterminal e um
     * terminal para a composicao da mesma.
     */
    /*public void adicionaUmaProducao(String s, Producao producao) {
     producao.origem = new Simbolo(s, 1);
     producao.terminal = new SimboloAlfabeto(s.substring(0, 1));
     try {
     producao.naoTerminal = new Simbolo(s.substring(1, 2), 1);
     } catch (Exception e) {
     producao.naoTerminal = new Simbolo("", 1);
     }
     producoesDaGramatica.add(producao);
     }*/
    //AUTOMATO
    /**
     * Função que recebe um novo alfabeto quando ao automato é ressetado.
     *
     * @return Um novo alfabeto
     */
    public String retornaAlfabeto() {
        String alfabeto;
        try {
            alfabeto = JOptionPane.showInputDialog("Digite o alfabeto do seu autômato separado por virgulas, sem espaços. (Ex.a,b,c)");
        } catch (Exception e) {
            return "";
        }
        return alfabeto;
    }

    /**
     * Função que cria as colunas a partir do alfabeto inserido pelo usuario
     */
    public void criarColunasAPartirDoAlfabeto() {
        dataAutomato = new Object[0][0];

        nomeColunasAutomato = new String[automato.alfabeto.size() + 1];

        nomeColunasAutomato[0] = "δ";
        for (int i = 0; i < automato.alfabeto.size(); i++) {
            nomeColunasAutomato[i + 1] = automato.alfabeto.get(i).toString();
        }

        modeloAutomato = new DefaultTableModel(dataAutomato, nomeColunasAutomato);
        tabelaAutomato.setModel(modeloAutomato);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ER;
    private javax.swing.JButton adicionarLinhaAutomato;
    private javax.swing.JButton adicionarLinhaGramatica;
    private javax.swing.JButton complementar;
    private javax.swing.JButton determinizar;
    private javax.swing.JButton gramaticaAutomato;
    private javax.swing.JButton interseccao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton resetaAutomato;
    private javax.swing.JButton resetarER;
    private javax.swing.JButton resetarGramatica;
    private javax.swing.JButton salvarAutomato;
    private javax.swing.JButton salvarGramatica;
    private javax.swing.JTable tabelaAutomato;
    private javax.swing.JTable tabelaExpressaoAutomato;
    private javax.swing.JTable tabelaGramatica;
    private javax.swing.JButton transformarER;
    // End of variables declaration//GEN-END:variables
}
